name: 'Setup k8s testing cluster'
description: 'Setup k8s testing cluster'
inputs:
  k8s-version:
    description: 'K8s version'
    required: true
runs:
  using: "composite"
  steps:
  - name: K8s setup
    shell: bash
    run: |
      minikube config set vm-driver none
      minikube config set kubernetes-version v${{ inputs.k8s-version }}
      sudo minikube start
      sudo chown -R runner: /home/runner/.{mini,}kube/
      minikube update-context
      kubectl cluster-info
