name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.14", "1.15"]
        os: [ubuntu-latest]
        # os: [macos-latest, windows-latest, ubuntu-latest]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...

  container:
    name: Build Container
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Docker build
      run: docker build -t demo .

    - name: Docker save
      run: docker save demo -o /tmp/demo.tar

    - name: Docker upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: demo-image
        path: /tmp/demo.tar

  integration:
    name: Integration
    runs-on: ubuntu-latest
    needs: container
    strategy:
      matrix:
        k8s: ["1.15.11", "1.16.13"]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.14.2
        k8s-version: ${{ matrix.k8s }}

    - name: Setup k8s testing cluster
      uses: ./.github/actions/setup-minikube
      with:
        k8s-version: ${{ matrix.k8s }}

    - name: Download docker image
      uses: actions/download-artifact@v2
      with:
        name: demo-image

    - name: Load docker image
      run: |
        docker load -i demo.tar
        docker inspect demo

    - name: Testing environment setup
      run: |
        kubectl apply -f deploy.yaml
        kubectl rollout status deployment/demo -w --timeout=1m || kubectl get pod
        kubectl get svc -o wide
        kubectl get svc demo -o jsonpath="{$.spec.clusterIP}" >/tmp/ip.txt

    - name: Integration tests
      run: |
        export SERVER_ADDR=http://$(cat /tmp/ip.txt):80
        go test -tags=integration
