name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...

    - uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.14.2
        k8s-version: 1.15.1

    - name: K8s setup
      run: |
        minikube config set vm-driver none
        minikube config set kubernetes-version v1.15.1
        sudo minikube start
        sudo chown -R runner: /home/runner/.{mini,}kube/
        minikube update-context
        kubectl cluster-info

    - name: Testing environment setup
      run: |
        kubectl apply -f deploy.yaml
        kubectl rollout status deployment/demo -w
        kubectl get svc -o wide
        kubectl get svc demo -o jsonpath="{$.spec.clusterIP}" >/tmp/ip.txt
        curl -vLf -m 5 http://$(cat /tmp/ip.txt):80

    - name: Integration tests
      run: |
        go test -tags=integration
